project:
  type: website
  output-dir: docs

website:
  title: "QuantileRegressionEpi"
  site-url: "https://lawrence-mccandless.github.io/QuantileRegressionEpi/"
  description: "Quantile regression methods for gestational age, preterm birth, and epidemiology research by Lawrence McCandless."
  navbar:
    left:
      - href: index.qmd
        text: Home

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    
    meta:
      description: "Quantile regression methods for gestational age, preterm birth, and epidemiology research by Lawrence McCandless."
      keywords: "quantile regression, preterm birth, gestational age, epidemiology, Bayesian quantile regression, Lawrence McCandless"

    
  pdf:
    documentclass: article
    toc: true
    number-sections: true

editor: visual

execute:
  freeze: false