<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lawrence McCandless">
<meta name="dcterms.date" content="2026-06-01">
<meta name="keywords" content="Quantile regression, gestational age, preterm birth, pregnancy outcomes, epidemiology, statistical modeling">

<title>Quantile regression of gestational age and preterm birth for epidemiology research – QuantileRegressionEpi</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ddd961a2510921635943dfbbd19534c4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">QuantileRegressionEpi</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#quantile-regression-the-basic-idea" id="toc-quantile-regression-the-basic-idea" class="nav-link active" data-scroll-target="#quantile-regression-the-basic-idea"><span class="header-section-number">1</span> Quantile Regression: The Basic Idea</a></li>
  <li><a href="#example-gestational-age-and-preterm-birth-in-the-1958-perinatal-mortality-survey-pms" id="toc-example-gestational-age-and-preterm-birth-in-the-1958-perinatal-mortality-survey-pms" class="nav-link" data-scroll-target="#example-gestational-age-and-preterm-birth-in-the-1958-perinatal-mortality-survey-pms"><span class="header-section-number">2</span> Example: Gestational age and preterm birth in the 1958 Perinatal Mortality Survey (PMS)</a></li>
  <li><a href="#quantile-regression-with-a-single-predictor-variable" id="toc-quantile-regression-with-a-single-predictor-variable" class="nav-link" data-scroll-target="#quantile-regression-with-a-single-predictor-variable"><span class="header-section-number">3</span> Quantile regression with a single predictor variable</a></li>
  <li><a href="#implausible-results-illustrating-the-influence-of-discrete-outcomes" id="toc-implausible-results-illustrating-the-influence-of-discrete-outcomes" class="nav-link" data-scroll-target="#implausible-results-illustrating-the-influence-of-discrete-outcomes"><span class="header-section-number">4</span> Implausible results: Illustrating the influence of discrete outcomes</a></li>
  <li><a href="#dither-a-remedy-for-implausible-results-in-quantile-regression-with-discrete-outcomes" id="toc-dither-a-remedy-for-implausible-results-in-quantile-regression-with-discrete-outcomes" class="nav-link" data-scroll-target="#dither-a-remedy-for-implausible-results-in-quantile-regression-with-discrete-outcomes"><span class="header-section-number">5</span> Dither: A remedy for implausible results in quantile regression with discrete outcomes</a></li>
  <li><a href="#concluding-remarks" id="toc-concluding-remarks" class="nav-link" data-scroll-target="#concluding-remarks"><span class="header-section-number">6</span> Concluding Remarks</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">7</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Quantile regression of gestational age and preterm birth for epidemiology research</h1>
<p class="subtitle lead">Tutorial Essay and Methodological Note</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lawrence McCandless </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>Quantile regression is described for the epidemiology of gestational age and preterm birth. Unlike ordinary least squares regression, which models only the mean outcome, quantile regression models the entire gestational age distribution, including the lower tails associated with preterm birth. I illustrate the interpretation of quantile regression results and implementation in the R package <code>quantreg</code>. Using data from the 1958 UK Perinatal Mortality Survey, maternal albuminuria is shown to be associated with shorter gestational age, particularly among pregnancies in the lower quantiles of the gestational age distribution. Conventional quantile regression is also shown to produce implausible integer-valued coefficient estimates when gestational age is analyzed as a discrete outcome measured in days.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>Quantile regression, gestational age, preterm birth, pregnancy outcomes, epidemiology, statistical modeling</p>
  </div>
</div>

</header>


<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Lawrence McCandless</strong> is Professor, Faculty of Health Sciences, Simon Fraser University, 8888 University Drive, Burnaby BC V5A 1S6, Canada.</p>
<p>E-mail: <code>lmccandl@sfu.ca</code></p>
<p>R codes and a synthetic version of the PMS dataset used are available from the GitHub repository for this monograph:</p>
<p><a href="https://github.com/Lawrence-McCandless/QuantitleRegressionEpi" class="uri">https://github.com/Lawrence-McCandless/QuantitleRegressionEpi</a></p>
</div>
</div>
</div>
<p><strong>Key words and phrases:</strong> Quantile regression, gestational age, preterm birth, pregnancy outcomes, epidemiology, statistical modeling.</p>
<section id="quantile-regression-the-basic-idea" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Quantile Regression: The Basic Idea</h1>
<p>Quantile regression is a data analysis technique where quantiles of the outcome are modelled in relation to predictor variables <span class="citation" data-cites="davino2014quantile koenker2005quantile">(<a href="#ref-davino2014quantile" role="doc-biblioref">Davino, Furno, and Vistocco 2014</a>; <a href="#ref-koenker2005quantile" role="doc-biblioref">Koenker 2005</a>)</span>. It is an extension of least squares regression, which models averages. Quantile regression gives a richer description of the distribution of the outcome. It provides information about the entire distribution of the response, and this allows for a deeper understanding of how predictor variables influence different parts of the outcome distribution, not just the average.</p>
<p>This is useful in epidemiology research <span class="citation" data-cites="strickland2019ambient">(<a href="#ref-strickland2019ambient" role="doc-biblioref">Strickland et al. 2019</a>)</span>. For example, in child health studies we can model IQ scores for neurodevelopment, or the forced expiratory volume to measure lung function. In these settings, we might prefer to not use linear regression models for location and scale because it assumes a normally distributed model for the outcome data distribution. Quantile regression is more robust to heteroscedasticity and outliers.</p>
<p>The basic idea of quantile regression is that the investigator chooses a particular quantile, which is indexed the Greek letter <span class="math inline">\(\tau\)</span>, which ranges from zero to one (from 0% to 100%). Informally, a quantile is simply the same thing as a “percentile”, except that a percentile is a percentage whereas a quantile is a number between zero and one. If <span class="math inline">\(\tau=0.5\)</span> then the quantile is the median. If <span class="math inline">\(\tau=0.1\)</span>, then the quantile is the 10<span class="math inline">\(^{th}\)</span> percentile, meaning the bottom 10% of the distribution.</p>
<p>Quantile regression involves modeling the quantile of a dependent variable <span class="math inline">\(Y\)</span> in relation to a predictor variable <span class="math inline">\(X\)</span>. The model is written <span class="math display">\[\begin{aligned}
Q_{\tau} = \beta_{0 [\tau]} + \beta_{X [\tau]} X, \label{eq-fqr-qrmodel.univar.with.taus}
\end{aligned}\]</span> which has two unknown parameters that define the model: <span class="math inline">\(\beta_{0 [\tau]}\)</span> and <span class="math inline">\(\beta_{X [\tau]}\)</span>. The quantity <span class="math inline">\(\beta_{X [\tau]}\)</span> is the slope (regression coefficient) and <span class="math inline">\(\beta_{0 [\tau]}\)</span> is the y-intercept. The subscript <span class="math inline">\(\tau\)</span> is written to emphasize that the parameter depends on <span class="math inline">\(\tau\)</span>. For example, if <span class="math inline">\(\tau=0.1\)</span>, then slope <span class="math inline">\(\beta_{X [\tau=0.1]}\)</span> describes the change in the 0.1 quantile (the 10<span class="math inline">\(^{th}\)</span> percentile) for every one-unit increase in <span class="math inline">\(X\)</span>. The y-intercept parameter <span class="math inline">\(\beta_{0 [\tau]}\)</span> is equal to the <span class="math inline">\(\tau^{th}\)</span> quantile in the group with <span class="math inline">\(X=0\)</span>.</p>
<p>The true values of <span class="math inline">\(\beta_{0 [\tau]}\)</span> and <span class="math inline">\(\beta_{X [\tau]}\)</span> are unknown, and they must be estimated from the data <span class="math inline">\(Y_1, Y_2, \dots, Y_n\)</span> and <span class="math inline">\(X_1, X_2, \dots, X_n\)</span>. The conventional approach described here is to minimize the sum of the weighted absolute value of the residuals. This is called minimizing the quantile loss, or equivalently, the pinball loss because the absolute value of the residuals looks like a pinball machine. To explain in more detail, quantile regression calculates the quantities <span class="math inline">\(\hat{\beta}_{0 [\tau]}\)</span> and <span class="math inline">\(\hat{\beta}_{X [\tau]}\)</span> which make the sum <span id="eq-fqr-QRobjFunction"><span class="math display">\[\begin{aligned}
\sum_{i=1}^n \rho_\tau\Big( Y_i - (\hat{\beta}_{0 [\tau]} + \hat{\beta}_{X [\tau]} X_i) \Big)
\end{aligned} \tag{1}\]</span></span> as small as possible, where <span class="math inline">\(\rho_\tau(.)\)</span> is the pinball loss function, and it is the absolute value of the residual <span class="math inline">\(Y_i - (\beta_{0 [\tau]} + \beta_{X [\tau]} X_i)\)</span> multiplied by <span class="math inline">\(\tau\)</span> or <span class="math inline">\(1-\tau\)</span>.</p>
<p><span class="math display">\[\rho_\tau(u) =
\begin{cases}
\tau |u|, &amp; \text{if } u \geq 0, \\
(1-\tau)|u|, &amp; \text{if } u &lt; 0.
\end{cases}\]</span></p>
<p>The minimization in equation <a href="#eq-fqr-QRobjFunction" class="quarto-xref">Equation&nbsp;1</a> is called the quantile regression loss function, and we choose the model that minimizes the loss. This results in estimating quantiles. To understand how the model fitting works, it is useful to compare quantile regression to ordinary least squares regression where we minimize the sum of the squares of the residuals, which is written <span class="math display">\[\sum_{i=1}^n \Big( Y_i - (\hat{\beta}_{0 [\tau]} + \hat{\beta}_{X [\tau]} X_i) \Big)^2.\]</span> We illustrate quantile regression using the R package <code>quantreg</code>.</p>
</section>
<section id="example-gestational-age-and-preterm-birth-in-the-1958-perinatal-mortality-survey-pms" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Example: Gestational age and preterm birth in the 1958 Perinatal Mortality Survey (PMS)</h1>
<p>Early gestational age is an important determinant of infant morbidity and mortality <span class="citation" data-cites="goldenberg2008epidemiology">(<a href="#ref-goldenberg2008epidemiology" role="doc-biblioref">Goldenberg et al. 2008</a>)</span>. It is measured on a discrete scale where the unit of analysis is typically weeks or days. Gestational age is not symmetrically distributed, and it has a long left tail, which corresponds to infants born too soon. At the upper end of the distribution, the right tail ends abruptly due to the modern obstetric practice of induction of labour late in pregnancy. In perinatal epidemiology, we are interested in the entire shape of the distribution, not just the mean.</p>
<p>We illustrate these ideas using data from the 1958 UK Perinatal Mortality Study (PMS) from the UK Data Service <span class="citation" data-cites="NCDS_UKDS">(<a href="#ref-NCDS_UKDS" role="doc-biblioref">Centre for Longitudinal Studies 2024</a>)</span>. This was a longitudinal cohort study following the lives of several thousand individuals born in a single week in England, Scotland and Wales. The data are contained in the file <code>pms.csv</code>, which is available from the GitHub repository of this article. The data include information from 2,540 mother and child pairs, and measurements of gestational age, measured in days, are contained in the <code>gestage</code> variable. For illustration of quantile regression, we focus on the influence of albuminuria on gestational age. Albuminuria (<code>album</code> variable coded as 1 or 0) is a symptom of pregnancy-induced high blood pressure (preeclampsia), which is a known risk factor for preterm birth and growth restriction. R codes and a synthetic version of the PMS dataset are available from the GitHub repository for this monograph at <a href="https://github.com/Lawrence-McCandless/QuantileRegressionEpidemiology" class="uri">https://github.com/Lawrence-McCandless/QuantileRegressionEpidemiology</a>.</p>
<p>We begin by calculating descriptive statistics for gestational age, stratified by albuminuria level of the mother during pregnancy. Using the <code>quantile()</code> command in R, we have</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">quantile</span>(pms<span class="sc">$</span>ga, <span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="fl">0.9</span>), <span class="at">type=</span><span class="dv">1</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span><span class="sc">% 25%</span> <span class="dv">50</span><span class="sc">% 75%</span> <span class="dv">90</span>%</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="dv">268</span> <span class="dv">275</span> <span class="dv">282</span> <span class="dv">289</span> <span class="dv">294</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>and the results are summarized in Table <strong>?@tbl-fqr-pmsalbumvsga</strong>, which also includes the frequency of preterm births, defined as births shorter than 259 days (37 weeks).</p>
<table class="caption-top table">
<caption>Distribution of gestational age and the frequency of preterm birth in the PMS dataset, stratified by albuminuria level.</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>Albuminuria</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">0.1</th>
<th style="text-align: right;">0.25</th>
<th style="text-align: right;">0.5</th>
<th style="text-align: right;">0.75</th>
<th style="text-align: right;">0.9</th>
<th style="text-align: right;">count</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Yes</td>
<td style="text-align: right;">182</td>
<td style="text-align: right;">278.3</td>
<td style="text-align: right;">13.2</td>
<td style="text-align: right;">260</td>
<td style="text-align: right;">272</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">285</td>
<td style="text-align: right;">293</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">5.5%</td>
</tr>
<tr class="even">
<td>No</td>
<td style="text-align: right;">2358</td>
<td style="text-align: right;">281.0</td>
<td style="text-align: right;">12.7</td>
<td style="text-align: right;">268</td>
<td style="text-align: right;">275</td>
<td style="text-align: right;">282</td>
<td style="text-align: right;">289</td>
<td style="text-align: right;">295</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">4.1%</td>
</tr>
<tr class="odd">
<td>All</td>
<td style="text-align: right;">2540</td>
<td style="text-align: right;">280.9</td>
<td style="text-align: right;">12.8</td>
<td style="text-align: right;">268</td>
<td style="text-align: right;">275</td>
<td style="text-align: right;">282</td>
<td style="text-align: right;">289</td>
<td style="text-align: right;">294</td>
<td style="text-align: right;">106</td>
<td style="text-align: right;">4.2%</td>
</tr>
</tbody>
</table>
<p>From the results it appears that albuminuria is associated with a shorter gestational age. Furthermore, the reduction is greatest at the lower end of the distribution of gestational age. For example, at the median, we see a 2-day reduction in gestational age (280 days versus 282 days), whereas at the <span class="math inline">\(\tau=0.1\)</span> quantile (10<span class="math inline">\(^{th}\)</span> percentile) we see an 8-day reduction (260 days versus 268 days). A <span class="math inline">\(&gt;1\)</span> week reduction in gestational age is clinically significant because the normal duration of pregnancy is 40 weeks, whereas an infant born at less than 37 weeks is classified as preterm. Moreover, the shift in the distribution of gestational age is not apparent based on a comparison of means. The mean is 278.3 days for mother with albuminuria versus 281.0 days in mothers without. In Table <strong>?@tbl-fqr-pmsalbumvsga</strong>, we see that there are a total of 106 preterm births, and that albuminuria is associated with a 31% increase in the frequency of preterm birth (5.5% versus 4.2%).</p>
</section>
<section id="quantile-regression-with-a-single-predictor-variable" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Quantile regression with a single predictor variable</h1>
<p>To motivate quantile regression, <a href="#fig-fqr-pmdescriptive-ga" class="quarto-xref">Figure&nbsp;1</a> shows the gestational age distribution, including the quantile function. As expected the distribution of gestational age has a long left tail.</p>
<div id="fig-fqr-pmdescriptive-ga" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fqr-pmdescriptive-ga-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig-fqr-pmdescriptive-ga.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fqr-pmdescriptive-ga-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Distribution of gestational age in the PMS dataset. Illustration of the probability density function <span class="math inline">\(f(x)\)</span>, the cumulative distribution function <span class="math inline">\(F(x)\)</span>, and the quantile function <span class="math inline">\(F^{-1}(\tau)\)</span>. The dashed line indicates the threshold for preterm birth (<span class="math inline">\(&lt;259\)</span> days).
</figcaption>
</figure>
</div>
<p>To examine the influence of albuminuria on gestational age, <a href="#fig-fqr-pmsdescriptiveAlbumvsga" class="quarto-xref">Figure&nbsp;2</a> shows the distribution of gestational age stratified by albuminuria level. The red curve is shifted to the left, which illustrates that infants of mothers with albuminuria have shorter gestational age.</p>
<div id="fig-fqr-pmsdescriptiveAlbumvsga" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fqr-pmsdescriptiveAlbumvsga-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig-fqr-pmsdescriptiveAlbumvsga.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fqr-pmsdescriptiveAlbumvsga-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Distribution of gestational age stratified by albuminuria level. The red curve describes mothers with albuminuria, whereas the black curve represents mothers without albuminuria. The dashed line indicates the threshold for preterm birth (<span class="math inline">\(&lt;259\)</span> days).
</figcaption>
</figure>
</div>
<p>Accordingly, we applied quantile regression to the data with <code>ga</code> as the dependent variable and <code>album</code> as the predictor variable. Subsequently, we considered adjustment for additional risk factors for preterm birth. We use the R function <code>rq()</code> in the <code>quantreg</code> package to fit quantile regression models.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">summary</span>(<span class="fu">rq</span>(ga <span class="sc">~</span> album, <span class="at">tau=</span><span class="fl">0.1</span>, <span class="at">data=</span>pms))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>Call<span class="sc">:</span> <span class="fu">rq</span>(<span class="at">formula =</span> ga <span class="sc">~</span> album, <span class="at">tau =</span> <span class="fl">0.1</span>, <span class="at">data =</span> pms)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>tau<span class="sc">:</span> [<span class="dv">1</span>] <span class="fl">0.1</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>Coefficients<span class="sc">:</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>            Value     Std. Error t value   <span class="fu">Pr</span>(<span class="sc">&gt;</span><span class="er">|</span>t<span class="sc">|</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>(Intercept) <span class="fl">268.00000</span>   <span class="fl">0.48725</span>  <span class="fl">550.02221</span>   <span class="fl">0.00000</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>album        <span class="sc">-</span><span class="fl">8.00000</span>   <span class="fl">2.24580</span>   <span class="sc">-</span><span class="fl">3.56221</span>   <span class="fl">0.00037</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>From the R output, we have the point estimates <span class="math inline">\(\hat{\beta}_{X [\tau]}=-8.0\)</span> and <span class="math inline">\(\hat{\beta}_{0 [\tau]}=268\)</span>, and the equation for the <span class="math inline">\(\tau=0.1\)</span> quantile is given by <span class="math inline">\(Q_{\tau}(Y) = 268.0 - 8.0 X\)</span>. By default, the <code>rq(.)</code> command uses the <code>"nid"</code> option <span class="citation" data-cites="davino2014quantile koenker2005quantile">(<a href="#ref-davino2014quantile" role="doc-biblioref">Davino, Furno, and Vistocco 2014</a>; <a href="#ref-koenker2005quantile" role="doc-biblioref">Koenker 2005</a>)</span>.</p>
<p>The quantile regression results are illustrated in further detail in Table <strong>?@tbl-fqr-pmsbetasqr</strong>. For comparison, two other analyses are also included: 1) ordinary least squares (OLS) regression of <code>ga</code> on <code>album</code>, which models the mean of gestational age, and 2) logistic regression analysis of <code>preterm</code> on <code>album</code>, where preterm birth is defined as gestational age less than 259 days (<code>preterm = ga &lt; 259</code>).</p>
<table class="caption-top table">
<caption>Quantile regression, OLS regression, and logistic regression results. Quantile regression uses <code>ga</code> as the dependent variable and <code>album</code> as the predictor. The logistic model uses <code>preterm</code> as the dependent variable. For quantile regression, the <code>rq(.)</code> command uses the default option <code>se="nid"</code> to compute standard errors and confidence intervals.</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th><span class="math inline">\(\tau\)</span></th>
<th><span class="math inline">\(\hat{\beta}_{X[\tau]}\)</span></th>
<th>SE</th>
<th>95% CI</th>
<th><span class="math inline">\(\hat{\beta}_{0[\tau]}\)</span></th>
<th>SE</th>
<th>95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Quantile regression</td>
<td>0.9</td>
<td>-2.00</td>
<td>0.95</td>
<td>(-3.86, -0.14)</td>
<td>295.00</td>
<td>0.37</td>
<td>(294.28, 295.72)</td>
</tr>
<tr class="even">
<td></td>
<td>0.75</td>
<td>-4.00</td>
<td>1.04</td>
<td>(-6.04, -1.96)</td>
<td>289.00</td>
<td>0.36</td>
<td>(288.29, 289.71)</td>
</tr>
<tr class="odd">
<td></td>
<td>0.5</td>
<td>-2.00</td>
<td>1.08</td>
<td>(-4.12, 0.12)</td>
<td>282.00</td>
<td>0.29</td>
<td>(281.43, 282.57)</td>
</tr>
<tr class="even">
<td></td>
<td>0.25</td>
<td>-3.00</td>
<td>1.33</td>
<td>(-5.61, -0.39)</td>
<td>275.00</td>
<td>0.27</td>
<td>(274.47, 275.53)</td>
</tr>
<tr class="odd">
<td></td>
<td>0.1</td>
<td>-8.00</td>
<td>2.25</td>
<td>(-12.40, -3.60)</td>
<td>268.00</td>
<td>0.49</td>
<td>(267.04, 268.96)</td>
</tr>
<tr class="even">
<td>OLS regression</td>
<td>-</td>
<td>-2.76</td>
<td>0.98</td>
<td>(-4.69, -0.84)</td>
<td>281.05</td>
<td>0.26</td>
<td>(280.53, 281.56)</td>
</tr>
<tr class="odd">
<td>Logistic regression</td>
<td>-</td>
<td>0.58</td>
<td>0.30</td>
<td>(0.00, 1.16)</td>
<td>-3.07</td>
<td>0.10</td>
<td>(-3.26, -2.87)</td>
</tr>
</tbody>
</table>
<p>The results show an overall pattern where albuminuria is associated with shorter gestational age, particularly among pregnancies in the lower quantiles of the gestational age distribution. In Table <strong>?@tbl-fqr-pmsbetasqr</strong>, the regression coefficients <span class="math inline">\(\hat{\beta}_{X [\tau]}\)</span>, for various <span class="math inline">\(\tau\)</span>, are both negative and precise. Moreover, we see the advantages of quantile regression compared to OLS regression and logistic regression. OLS identifies a statistically significant inverse association between albuminuria and gestational age. But the regression coefficient for the difference in the means (<span class="math inline">\(\hat{\beta}_X=-2.76\)</span> days) gives a poor description of the overall relationship in the data. On the other hand, logistic regression dichotomizes the gestational age variable. This has the advantage of giving results that are easier to interpret at the expense of discarding information about the rest of the distribution. The logistic regression coefficient is 0.58, which corresponds to an odds ratio of 1.79 for the association between albuminuria and higher odds of preterm birth. However, the estimate is relatively imprecise with a wide 95% confidence interval 1.0 to 3.19.</p>
</section>
<section id="implausible-results-illustrating-the-influence-of-discrete-outcomes" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Implausible results: Illustrating the influence of discrete outcomes</h1>
<p>A curious feature of Table <strong>?@tbl-fqr-pmsbetasqr</strong> is that quantile regression coefficients are always integers (i.e.&nbsp;numbers like <span class="math inline">\(-2,-1, 0, 1, 2, \dots\)</span> etc). This makes the results look implausible <span class="citation" data-cites="alampi2025performance">(<a href="#ref-alampi2025performance" role="doc-biblioref">Alampi, Lanphear, and McCandless 2025</a>)</span>. For example, when <span class="math inline">\(\tau=0.1\)</span> then <span class="math inline">\(\hat{\beta}_{X [\tau]} = -8.00\)</span>. These integer-valued coefficient estimates from quantile regress are not an accident. They occurs because the <code>quantreg</code> software uses the simplex algorithm <span class="citation" data-cites="koenker2005quantile">(<a href="#ref-koenker2005quantile" role="doc-biblioref">Koenker 2005</a>)</span>. When <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span> are discrete, then the software will only produce integer valued parameters. The software that minimizes the pinball loss in equation <a href="#eq-fqr-QRobjFunction" class="quarto-xref">Equation&nbsp;1</a> cannot explore a continuous range of possible values for the unknown parameters <span class="math inline">\(\beta_{X [\tau]}\)</span> and <span class="math inline">\(\beta_{0 [\tau]}\)</span>. Instead it considers a restricted collection of fitted models called basic solutions, which are the linear models that directly through pairs of data points. The simplex algorithm works well for quantile regression with continuous outcomes because the gaps (spacings) between neighboring data points shrink to zero in large datasets. But it can generate implausible results for discrete outcomes because the basic solutions are heavily influenced by discretization arising from rounding of the data. If the data are discrete then the output of quantile regression software is also discrete. See Koenker <span class="citation" data-cites="koenker2005quantile">(<a href="#ref-koenker2005quantile" role="doc-biblioref">Koenker 2005</a>)</span>, Section 2.2.1 for discussion.</p>
<p>To show why the results are implausible, it is helpful to consider multivariable quantile regression analysis with several predictor variables. We include three additional predictors of gestational age: Child sex, marital status, and smoking status. These are encoded in the zero-one variables <code>female</code>, <code>single</code>, and zero-one indicator variables for smoking (<code>smoke1</code> for former smoker versus non-smoker, and <code>smoke2</code> for smoker versus non-smoker). We fit the quantile regression model <span class="math display">\[\begin{aligned}
Q_{\tau} = \beta_{0 [\tau]} + \beta_{1 [\tau]} album + \beta_{2 [\tau]} female + \beta_{3 [\tau]} single +\beta_{4 [\tau]} smoke1 + \beta_{5 [\tau]} smoke2\label{eq-fqr-qrmodel.mlr}
\end{aligned}\]</span> using the R code:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">summary</span>(<span class="fu">rq</span>(ga <span class="sc">~</span> album <span class="sc">+</span> female <span class="sc">+</span> single <span class="sc">+</span> <span class="fu">as.factor</span>(smk), <span class="at">tau=</span><span class="fl">0.1</span>, <span class="at">data=</span>pms))</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>Call<span class="sc">:</span> <span class="fu">rq</span>(<span class="at">formula =</span> ga <span class="sc">~</span> album <span class="sc">+</span> female <span class="sc">+</span> single <span class="sc">+</span> <span class="fu">as.factor</span>(smk), <span class="at">tau =</span> <span class="fl">0.1</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> pms)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>tau<span class="sc">:</span> [<span class="dv">1</span>] <span class="fl">0.1</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>Coefficients<span class="sc">:</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>                Value     Std. Error t value   <span class="fu">Pr</span>(<span class="sc">&gt;</span><span class="er">|</span>t<span class="sc">|</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>(Intercept)     <span class="fl">268.00000</span>   <span class="fl">0.77273</span>  <span class="fl">346.82260</span>   <span class="fl">0.00000</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>album            <span class="sc">-</span><span class="fl">6.00000</span>   <span class="fl">1.88352</span>   <span class="sc">-</span><span class="fl">3.18553</span>   <span class="fl">0.00146</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>female            <span class="fl">1.00000</span>   <span class="fl">0.94601</span>    <span class="fl">1.05707</span>   <span class="fl">0.29058</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>single           <span class="sc">-</span><span class="fl">4.00000</span>   <span class="fl">4.98359</span>   <span class="sc">-</span><span class="fl">0.80263</span>   <span class="fl">0.42226</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="fu">as.factor</span>(smk)<span class="dv">1</span>   <span class="fl">2.00000</span>   <span class="fl">1.07956</span>    <span class="fl">1.85261</span>   <span class="fl">0.06406</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="fu">as.factor</span>(smk)<span class="dv">2</span>  <span class="sc">-</span><span class="fl">2.00000</span>   <span class="fl">1.20993</span>   <span class="sc">-</span><span class="fl">1.65298</span>   <span class="fl">0.09846</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Again the regression coefficients are integers. To show this behavior more clearly, Figure <a href="#fig-fqr-pmsbetasqr.mlr" class="quarto-xref">Figure&nbsp;3</a> plots the estimated quantile regression coefficients for the different variables when <span class="math inline">\(\tau\)</span> ranges from zero to one. Random sampling errors are ignored (e.g.&nbsp;95% confidence intervals). We see that the curves bounce around half-haphazardly because they are stuck on integer values. Because <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span> are discrete, the <code>quantreg</code> package will only produce integer valued estimates of the model parameters.</p>
<div id="fig-fqr-pmsbetasqr.mlr" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fqr-pmsbetasqr.mlr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig-fqr-pmsbetasqr.mlr.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fqr-pmsbetasqr.mlr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Results of multivariable quantile regression with as the dependent variable and , and as predictor variables. The curves are quantile regression coefficients where the horizontal axis shows the different quantiles that range from zero to one.
</figcaption>
</figure>
</div>
<p>Consider the gestational age of female infants. It is already known that females have slightly shorter average duration of pregnancy than males among full-term births in many human populations <span class="citation" data-cites="Divon2002">(<a href="#ref-Divon2002" role="doc-biblioref">Divon et al. 2002</a>)</span>. But the difference between males and females is small (e.g.&nbsp;280.6 days for males versus 279.8 days for females by one estimate <span class="citation" data-cites="Divon2002">(<a href="#ref-Divon2002" role="doc-biblioref">Divon et al. 2002</a>)</span>). Thus we already know that the effect of sex on gestational age is non-zero. But it is also unlikely to be exactly equal to 1.0 days because a single day is an arbitrary unit of measurement. In this example, the size of the target parameters is roughly the same as the size of the rounding error in the gestational age scale. The simplex algorithm for fitting quantile regression gives results where the accuracy of estimates is influenced discreteness of the outcome in way that is seems unreasonable.</p>
<p>A further consequence of the implausible point estimates is that it propagates into the calculation of confidence intervals and p-values for uncertainty assessment. The standard errors by default are produced using the option <code>se="nid"</code> computed under the assumption that gestational age is continuous and that the errors are not necessarily independent and identically distributed. A discussion of statistical inference in quantile regression is beyond the scope of this monograph, but the point is the default t-values and p-values from the <code>quantreg</code> package depend on the implausible point estimates.</p>
</section>
<section id="dither-a-remedy-for-implausible-results-in-quantile-regression-with-discrete-outcomes" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Dither: A remedy for implausible results in quantile regression with discrete outcomes</h1>
<p>There are different strategies to fix the implausible results from quantile regression with discrete outcomes <span class="citation" data-cites="alampi2025performance">(<a href="#ref-alampi2025performance" role="doc-biblioref">Alampi, Lanphear, and McCandless 2025</a>)</span>. One option is to use dithering <span class="citation" data-cites="machado2005quantiles">(<a href="#ref-machado2005quantiles" role="doc-biblioref">Machado and Silva 2005</a>)</span>. Dithering is a procedure that adds uniform noise to the outcome variable <span class="math inline">\(Y\)</span> to account for the discreteness. For example, if the duration of gestation is <code>ga=</code>280 days, then we randomly add a number ranging from -0.5 to 0.5 days to 280. The resulting dithered outcome variable is fed into quantile regression.</p>
<p>To dither the gestational age variable, we use the <code>dither()</code> command in the <code>quantreg</code> package to create a new variable <code>ga_d</code>.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> pms<span class="sc">$</span>ga_d <span class="ot">&lt;-</span> <span class="fu">dither</span>(pms<span class="sc">$</span>ga)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">head</span>(pms<span class="sc">$</span>ga)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="dv">303</span> <span class="dv">261</span> <span class="dv">285</span> <span class="dv">298</span> <span class="dv">277</span> <span class="dv">303</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">head</span>(pms<span class="sc">$</span>ga_d)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="fl">303.2863</span> <span class="fl">260.9340</span> <span class="fl">284.9133</span> <span class="fl">298.4330</span> <span class="fl">277.4567</span> <span class="fl">303.3706</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>We then feed the dithered outcome <code>ga_d</code> into quantile regression in place of the original variable <code>ga</code>. The results are given as</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">summary</span>(<span class="fu">rq</span>(ga_d <span class="sc">~</span> album <span class="sc">+</span> female <span class="sc">+</span> single <span class="sc">+</span> <span class="fu">as.factor</span>(smk), <span class="at">tau=</span><span class="fl">0.1</span>, <span class="at">data=</span>pms))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>Call<span class="sc">:</span> <span class="fu">rq</span>(<span class="at">formula =</span> ga_d <span class="sc">~</span> album <span class="sc">+</span> female <span class="sc">+</span> single <span class="sc">+</span> <span class="fu">as.factor</span>(smk),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">tau =</span> <span class="fl">0.1</span>, <span class="at">data =</span> pms)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>tau<span class="sc">:</span> [<span class="dv">1</span>] <span class="fl">0.1</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>Coefficients<span class="sc">:</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>                Value     Std. Error t value   <span class="fu">Pr</span>(<span class="sc">&gt;</span><span class="er">|</span>t<span class="sc">|</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>(Intercept)     <span class="fl">267.96566</span>   <span class="fl">0.79485</span>  <span class="fl">337.12761</span>   <span class="fl">0.00000</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>album            <span class="sc">-</span><span class="fl">6.51431</span>   <span class="fl">1.69716</span>   <span class="sc">-</span><span class="fl">3.83835</span>   <span class="fl">0.00013</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>female            <span class="fl">1.33697</span>   <span class="fl">1.00523</span>    <span class="fl">1.33001</span>   <span class="fl">0.18364</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>single           <span class="sc">-</span><span class="fl">3.20120</span>   <span class="fl">4.76561</span>   <span class="sc">-</span><span class="fl">0.67173</span>   <span class="fl">0.50182</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="fu">as.factor</span>(smk)<span class="dv">1</span>   <span class="fl">1.77985</span>   <span class="fl">1.14689</span>    <span class="fl">1.55189</span>   <span class="fl">0.12081</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="fu">as.factor</span>(smk)<span class="dv">2</span>  <span class="sc">-</span><span class="fl">1.87375</span>   <span class="fl">1.28035</span>   <span class="sc">-</span><span class="fl">1.46347</span>   <span class="fl">0.14346</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Based on this R output, we can see that the quantile regression results are more reasonable because the point estimates <span class="math inline">\(\hat{\beta}_{1 [\tau]}, \hat{\beta}_{2 [\tau]} \dots , \hat{\beta}_{5 [\tau]}\)</span> are no longer constrained to lie on the set of integers. Because the results depend on the specific dithered values of gestational age, it is recommended to average over the dithered samples <span class="citation" data-cites="machado2005quantiles">(<a href="#ref-machado2005quantiles" role="doc-biblioref">Machado and Silva 2005</a>)</span>. This is achieved by using Monte Carlo simulation to replace the single dithered values with several possible values, and then repeat the analysis each time to average over uncertainty. The R codes for dithering are given in the supplementary GitHub repository for this monograph.</p>
<p>Figure <a href="#fig-fqr-pmsbetasqr.mlr.dithered" class="quarto-xref">Figure&nbsp;4</a> shows the results of multivariable quantile regression after averaging over the dithered values of gestational age. Thus Figure <a href="#fig-fqr-pmsbetasqr.mlr.dithered" class="quarto-xref">Figure&nbsp;4</a> is identical to Figure <a href="#fig-fqr-pmsbetasqr.mlr" class="quarto-xref">Figure&nbsp;3</a>, except that the results account for discreteness of gestational age due to rounding. The quantile coefficient curves are much smoother. Thus the results are more plausible because the estimated values of <span class="math inline">\(\hat{\beta}_{1 [\tau]}, \hat{\beta}_{2 [\tau]} \dots , \hat{\beta}_{5 [\tau]}\)</span> are not stuck on the set of integers (i.e.&nbsp;numbers like <span class="math inline">\(-2,-1, 0, 1, 2, \dots\)</span>).</p>
<div id="fig-fqr-pmsbetasqr.mlr.dithered" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fqr-pmsbetasqr.mlr.dithered-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig-fqr-pmsbetasqr.mlr.dithered.svg" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fqr-pmsbetasqr.mlr.dithered-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Quantile regression with dithering of . The curves are quantile regression coefficients for the predictor variables , and , where the horizontal axis shows the different quantiles that range from zero to one.
</figcaption>
</figure>
</div>
<p>Returning to the example of the influence of female sex on gestational age, we see in Figure <a href="#fig-fqr-pmsbetasqr.mlr.dithered" class="quarto-xref">Figure&nbsp;4</a> that the quantile coefficients curve is greater than zero. In contrast, conventional quantile regression gives only estimates that are 0.00 or +1.00 which are artifacts of the rounding error of gestational age. Certainly some caution in interpretation is warranted regarding the role of random sampling error in the estimates. If we assume that the median duration of gestation is 40 weeks (280 days), then the standard error comparing equal-sized groups of females versus males <span class="math inline">\(n_0=n_1=1250\)</span> at the median is roughly equal to <span class="math inline">\(\sqrt{\xi ^2(1/n_1 + 1/n_2)}\)</span>, where <span class="math inline">\(\xi^2 = \tau(1-\tau)/f(280 \textrm{ days})^2\)</span>. If the density at 280 days is 2%, then the standard error is approximately equal to 1. Thus the results for female gender are imprecise. However, imprecise results from random sampling error does not justify poor accuracy of point estimation.</p>
</section>
<section id="concluding-remarks" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Concluding Remarks</h1>
<p>A critique of the preceding analysis is that quantile regression can only be used to analyze continuous outcomes, and it should not be applied to discrete outcomes. This is described, for example, in Koenker <span class="citation" data-cites="koenker2005quantile">(<a href="#ref-koenker2005quantile" role="doc-biblioref">Koenker 2005</a>)</span>, Section 3.2, and Davino, Furno and Vistocc <span class="citation" data-cites="davino2014quantile">(<a href="#ref-davino2014quantile" role="doc-biblioref">Davino, Furno, and Vistocco 2014</a>)</span>, Section 1.1.1, which stipulate that the distribution of the outcome <span class="math inline">\(Y\)</span> should have a continuous probability density. This requirement justifies the large-sample confidence intervals and p-values for quantile regression. Furthermore, when quantile regression is applied to large datasets with continuous outcomes, then implausible results that we saw in Section 4 are unusual because the gaps (spacings) between neighboring data points shrink to zero. But on the other hand, the process of fitting a quantile regression model by minimizing the pinball loss in equation <a href="#eq-fqr-QRobjFunction" class="quarto-xref">Equation&nbsp;1</a> does not actually require that the outcome <span class="math inline">\(Y\)</span> is continuous. To put it bluntly: Equation <a href="#eq-fqr-QRobjFunction" class="quarto-xref">Equation&nbsp;1</a> doesn’t care if <span class="math inline">\(Y\)</span> is continuous or not.</p>
<p>Moreover, the requirement of a continuous outcome in quantile regression is limiting in practice. In many applications the outcome variable is not truly continuous. In statistics, the word “continuous” is used in a narrow mathematical sense for a scale in which any real number in its range is a possible value. However, the word “continuous” in a practical sense means a scale that is very fine for the application at hand. In the PMS data example, the true gestational age of an infant is a continuous quantity: It is the duration of human pregnancy from conception until birth of the infant. But in practice, gestational age is rarely measured with precision exceeding <span class="math inline">\(\pm 1\)</span> day because the exact timing of the start of conception is difficult to measure precisely.</p>
<p>And yet, despite the discreteness of <span class="math inline">\(Y\)</span> that arises from rounding errors in the data, epidemiologists still wish to use quantile regression for outcomes like gestational age. The method provides information about the entire distribution of the response, and this allows for a deeper understanding of how predictor variables influence different parts of the outcome distribution, not just the average. The benefits of quantile regression are clearly displayed in Table <strong>?@tbl-fqr-pmsbetasqr</strong>: We see that albuminuria has the largest impact at the lower end of the gestational age distribution. This finding invites inquiry into understanding the reasons for this large effect. For example, some infants in the PMS study may be uniquely susceptible to maternal illness during pregnancy.</p>
<p>There are different strategies to fix the implausible results in quantile regression that result from rounding, and this is an ongoing area of research (e.g.&nbsp;see <span class="citation" data-cites="alampi2025performance">(<a href="#ref-alampi2025performance" role="doc-biblioref">Alampi, Lanphear, and McCandless 2025</a>)</span>). Section 5 uses dithering <span class="citation" data-cites="machado2005quantiles">(<a href="#ref-machado2005quantiles" role="doc-biblioref">Machado and Silva 2005</a>)</span>, which adds uniform noise to the outcome variable <span class="math inline">\(Y\)</span> to account for the discreteness. In fact, dithering can be viewed as an example of multiple imputation for missing data. In multiple imputation, we replace a single missing data point with one of several plausible, simulated values based on observed data using Monte Carlo simulation. The process can be repeated several times to average over the imputation uncertainty. Dithering can also be interpreted as an example of ordered categorical regression with a latent variable and cutpoints. Under this interpretation, the observed discrete outcome is viewed as a rounded or categorized version of an underlying continuous latent variable, and the added uniform noise approximates the uncertainty regarding the true value within each interval defined by the cutpoints. A different strategy to account for implausible results is to use Bayesian quantile regression <span class="citation" data-cites="Yang2016Posterior">(<a href="#ref-Yang2016Posterior" role="doc-biblioref">Yang, Wang, and He 2016</a>)</span>. This approach uses an asymmetric Laplace likelihood, and model fitting proceeds using Markov chain Monte Carlo instead of the usual pinball loss minimization. The advantage of Bayesian quantile regression is that it explores the entire parameter space instead of being restricted to integer-valued coefficients, and the result is the full posterior distribution for unknown parameters.</p>
</section>
<section id="references" class="level1" data-number="7">




</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">7 References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-alampi2025performance" class="csl-entry" role="listitem">
Alampi, Jessica D., Bruce P. Lanphear, and Lawrence C. McCandless. 2025. <span>“Performance of Quantile Regression Methods with Discrete Outcomes: A Simulation Study with Applications to Environmental Epidemiology.”</span> <em>Environmental Epidemiology</em> 9 (6): e432. <a href="https://doi.org/10.1097/EE9.0000000000000432">https://doi.org/10.1097/EE9.0000000000000432</a>.
</div>
<div id="ref-NCDS_UKDS" class="csl-entry" role="listitem">
Centre for Longitudinal Studies. 2024. <span>“National Child Development Study (NCDS), 1958–2024.”</span> UK Data Service. <a href="https://doi.org/10.5255/UKDA-Series-2000032">https://doi.org/10.5255/UKDA-Series-2000032</a>.
</div>
<div id="ref-davino2014quantile" class="csl-entry" role="listitem">
Davino, Cristina, Marilena Furno, and Domenico Vistocco. 2014. <em>Quantile Regression: Theory and Applications</em>. Wiley.
</div>
<div id="ref-Divon2002" class="csl-entry" role="listitem">
Divon, M. Y., M. Ferber, R. Nisell, and B. Westgren. 2002. <span>“Male Gender Predisposes to Prolongation of Pregnancy.”</span> <em>American Journal of Obstetrics and Gynecology</em> 187 (4): 1081–83. <a href="https://doi.org/10.1067/mob.2002.126645">https://doi.org/10.1067/mob.2002.126645</a>.
</div>
<div id="ref-goldenberg2008epidemiology" class="csl-entry" role="listitem">
Goldenberg, Robert L., Jennifer F. Culhane, Jay D. Iams, and Roberto Romero. 2008. <span>“Epidemiology and Causes of Preterm Birth.”</span> <em>The Lancet</em> 371 (9606): 75–84. <a href="https://doi.org/10.1016/S0140-6736(08)60074-4">https://doi.org/10.1016/S0140-6736(08)60074-4</a>.
</div>
<div id="ref-koenker2005quantile" class="csl-entry" role="listitem">
Koenker, Roger. 2005. <em>Quantile Regression</em>. Cambridge, UK: Cambridge University Press.
</div>
<div id="ref-machado2005quantiles" class="csl-entry" role="listitem">
Machado, José A. F., and J. M. C. Santos Silva. 2005. <span>“Quantiles for Counts.”</span> <em>Journal of the American Statistical Association</em> 100 (472): 1226–37. <a href="https://doi.org/10.1198/016214505000000330">https://doi.org/10.1198/016214505000000330</a>.
</div>
<div id="ref-strickland2019ambient" class="csl-entry" role="listitem">
Strickland, Matthew J., Ying Lin, Lyndsey A. Darrow, Joshua L. Warren, James A. Mulholland, and Howard H. Chang. 2019. <span>“Associations Between Ambient Air Pollutant Concentrations and Birth Weight: A Quantile Regression Analysis.”</span> <em>Epidemiology</em> 30 (5): 624–32. <a href="https://doi.org/10.1097/EDE.0000000000001040">https://doi.org/10.1097/EDE.0000000000001040</a>.
</div>
<div id="ref-Yang2016Posterior" class="csl-entry" role="listitem">
Yang, Yunwen, Huixia Judy Wang, and Xuming He. 2016. <span>“Posterior Inference in Bayesian Quantile Regression with Asymmetric Laplace Likelihood.”</span> <em>International Statistical Review</em> 84 (3): 327–44. <a href="https://doi.org/10.1111/insr.12114">https://doi.org/10.1111/insr.12114</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>